// Generated by jextract

package net.tinyio.nativesockets;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$5 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$5() {}
    static final StructLayout const$0 = MemoryLayout.structLayout(
        JAVA_INT.withName("s_addr")
    ).withName("in_addr");
    static final VarHandle const$1 = constants$5.const$0.varHandle(MemoryLayout.PathElement.groupElement("s_addr"));
    static final FunctionDescriptor const$2 = FunctionDescriptor.of(JAVA_INT,
        JAVA_INT
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "ntohl",
        constants$5.const$2
    );
    static final FunctionDescriptor const$4 = FunctionDescriptor.of(JAVA_SHORT,
        JAVA_SHORT
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "ntohs",
        constants$5.const$4
    );
}


