// Generated by jextract

package net.tinyio.nativesockets;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$7 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$7() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandleVariadic(
        "fcntl",
        constants$3.const$2
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "close",
        constants$5.const$2
    );
}


