// Generated by jextract

package net.tinyio.nativesockets;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
/**
 * {@snippet :
 * struct pollfd {
 *     int fd;
 *     short events;
 *     short revents;
 * };
 * }
 */
public class pollfd {

    public static MemoryLayout $LAYOUT() {
        return constants$6.const$2;
    }
    public static VarHandle fd$VH() {
        return constants$6.const$3;
    }
    /**
     * Getter for field:
     * {@snippet :
     * int fd;
     * }
     */
    public static int fd$get(MemorySegment seg) {
        return (int)constants$6.const$3.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * int fd;
     * }
     */
    public static void fd$set(MemorySegment seg, int x) {
        constants$6.const$3.set(seg, x);
    }
    public static int fd$get(MemorySegment seg, long index) {
        return (int)constants$6.const$3.get(seg.asSlice(index*sizeof()));
    }
    public static void fd$set(MemorySegment seg, long index, int x) {
        constants$6.const$3.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle events$VH() {
        return constants$6.const$4;
    }
    /**
     * Getter for field:
     * {@snippet :
     * short events;
     * }
     */
    public static short events$get(MemorySegment seg) {
        return (short)constants$6.const$4.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * short events;
     * }
     */
    public static void events$set(MemorySegment seg, short x) {
        constants$6.const$4.set(seg, x);
    }
    public static short events$get(MemorySegment seg, long index) {
        return (short)constants$6.const$4.get(seg.asSlice(index*sizeof()));
    }
    public static void events$set(MemorySegment seg, long index, short x) {
        constants$6.const$4.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle revents$VH() {
        return constants$6.const$5;
    }
    /**
     * Getter for field:
     * {@snippet :
     * short revents;
     * }
     */
    public static short revents$get(MemorySegment seg) {
        return (short)constants$6.const$5.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * short revents;
     * }
     */
    public static void revents$set(MemorySegment seg, short x) {
        constants$6.const$5.set(seg, x);
    }
    public static short revents$get(MemorySegment seg, long index) {
        return (short)constants$6.const$5.get(seg.asSlice(index*sizeof()));
    }
    public static void revents$set(MemorySegment seg, long index, short x) {
        constants$6.const$5.set(seg.asSlice(index*sizeof()), x);
    }
    public static long sizeof() { return $LAYOUT().byteSize(); }
    public static MemorySegment allocate(SegmentAllocator allocator) { return allocator.allocate($LAYOUT()); }
    public static MemorySegment allocateArray(long len, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(len, $LAYOUT()));
    }
    public static MemorySegment ofAddress(MemorySegment addr, Arena arena) { return RuntimeHelper.asArray(addr, $LAYOUT(), 1, arena); }
}


