// Generated by jextract

package net.isaiahp.tinyio.nativesockets;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$6 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$6() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "htonl",
        constants$5.const$2
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "htons",
        constants$5.const$4
    );
    static final StructLayout const$2 = MemoryLayout.structLayout(
        JAVA_INT.withName("fd"),
        JAVA_SHORT.withName("events"),
        JAVA_SHORT.withName("revents")
    ).withName("pollfd");
    static final VarHandle const$3 = constants$6.const$2.varHandle(PathElement.groupElement("fd"));
    static final VarHandle const$4 = constants$6.const$2.varHandle(PathElement.groupElement("events"));
    static final VarHandle const$5 = constants$6.const$2.varHandle(PathElement.groupElement("revents"));
}


