// Generated by jextract

package net.isaiahp.tinyio.nativesockets;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$4 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$4() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "shutdown",
        constants$3.const$2
    );
    static final FunctionDescriptor const$1 = FunctionDescriptor.of(RuntimeHelper.POINTER);
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "__errno_location",
        constants$4.const$1
    );
    static final StructLayout const$3 = MemoryLayout.structLayout(
        JAVA_SHORT.withName("sin_family"),
        JAVA_SHORT.withName("sin_port"),
        MemoryLayout.structLayout(
            JAVA_INT.withName("s_addr")
        ).withName("sin_addr"),
        MemoryLayout.sequenceLayout(8, JAVA_BYTE).withName("sin_zero")
    ).withName("sockaddr_in");
    static final VarHandle const$4 = constants$4.const$3.varHandle(PathElement.groupElement("sin_family"));
    static final VarHandle const$5 = constants$4.const$3.varHandle(PathElement.groupElement("sin_port"));
}


